export const GET_CAR_REQUEST = "GET_CAR_REQUEST";
export const GET_CAR_SUCCESS = "GET_CAR_SUCCESS";
export const GET_CAR_FALIURE = "GET_CAR_FALIURE";

export const GET_ID_REQUEST = "GET_ID_REQUEST";
export const GET_ID_SUCESS = "GET_ID_SUCESS";
export const GET_ID_FALIURE = "GET_ID_FALIURE";
