export const GET_LOCATION_REQU = "GET_LOCATION_REQU";
export const GET_LOCATION_SUCC = "GET_LOCATION_SUCC";
export const GET_LOCATION_FAIL = "GET_LOCATION_FAIL";

export const ADD_USER_LOC_REQUEST = "ADD_USER_LOC_REQUEST";
export const ADD_USER_LOC_SUCCESS = "ADD_USER_LOC_SUCCESS";
export const ADD_USER_LOC_FAILURE = "ADD_USER_LOC_FAILURE";

export const GET_USER_LOC_REQUEST = "GET_USER_LOC_REQUEST";
export const GET_USER_LOC_SUCCESS = "GET_USER_LOC_SUCCESS";
export const GET_USER_LOC_FAILURE = "GET_USER_LOC_FAILURE";
